### ISSUE TITLE
Footer / copyright wrapper not working.

### ISSUE THREAD

**Issue by Jank8** [stueja/ethereal-hugo-theme#1]
Copyright info is badly placed. I inspected hugo local and html5up website demo - wrapper is not working for hugo local. I cant find whats wrong. Also background is not showing up - missing bg.jpg and overlay.png
![hugo](https://user-images.githubusercontent.com/99371372/153311772-c07cd02b-e54f-40d1-a80c-e31f10fe8f6f.png)
![demo](https://user-images.githubusercontent.com/99371372/153311778-3784baf7-c3a7-4575-b847-9bd4f791105e.png)

**Comment by stueja** [comment]
@Jank8 , thank you very much. I fixed a runaway section and div tag. Please try again.

**Comment by Jank8** [comment]
> @Jank8 , thank you very much. I fixed a runaway section and div tag. Please try again.

Awewome, works. Quick question: when i put it on normal hosting, email form will be working right away?

**Comment by stueja** [comment]
Good to hear that, thanks for the feedback.

To make the form work, you'd have to replace the `#` in `<form method="post" action="#">` by a URL which can evaluate the POST data. Such a URL can be a simple PHP script on your own webserver or hosting. Maybe your hoster has an offer for such a service. If not, there are services like formspree which can handle the form.
