### ISSUE TITLE
Unmarshal failed: toml: expected 'true'

### ISSUE THREAD

**Issue by Jank8** [stueja/ethereal-hugo-theme#2]
WARN  Failed to read module config for "Ethereal" in "(...)\\themes\\Ethereal\\theme.toml": "_stream.toml:9:9": unmarshal failed: toml: expected 'true'

In new version of hugo error like above occurs.

**Comment by stueja** [comment]
@Jank8 thank you very much. Unfortunately, I haven't worked with hugo in the last years and I have no time to follow up with that warning message at the moment.
